# Generated by Django 5.1.6 on 2025-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
