# Generated by Django 5.1.6 on 2025-02-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_book_author_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
