# Generated by Django 5.1.6 on 2025-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/pages/'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpage',
            unique_together={('book', 'page_number')},
        ),
    ]
