# Generated by Django 5.1.6 on 2025-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_total_pages_alter_bookpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_books',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='main.book'),
        ),
    ]
