# Generated by Django 5.1.6 on 2025-02-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
